---
name: lint
run-name: "CI: ${{ github.triggering_actor }} on ${{ github.head_ref }} (${{ github.event_name }})"

on:
  push:
    branches:
      - master
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PIPENV_VENV_IN_PROJECT: true
  PIPENV_VENV_OUTSIDE: ${{ github.workspace }}/.venv
  ANSIBLE_COLLECTIONS_PATH: ${{ github.workspace }}/.ansible

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set Python version
        uses: actions/setup-python@v5
        id: pyversion
        with:
          python-version: '3.11'
      - name: Prepare
        shell: bash
        run: |
          python --version
          pip install --upgrade pipenv
      - name: Load dependencies from cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PIPENV_VENV_OUTSIDE }}
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}-${{ steps.pyversion.outputs.python-version }}
          restore-keys: |
            ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}-${{ steps.pyversion.outputs.python-version }}
      - name: Install dependencies
        shell: bash
        run: |
          pipenv install --python ${{ steps.pyversion.outputs.python-version }}
      - name: Save dependencies to cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PIPENV_VENV_OUTSIDE }}
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}-${{ steps.pyversion.outputs.python-version }}
      - name: Run yamllint
        shell: bash
        run: |
          pipenv run yamllint .
      - name: Install required collections
        shell: bash
        run: |
          pipenv run ansible-galaxy collection install community.docker
      - name: Run ansible-lint
        shell: bash
        run: |
          pipenv run ansible-lint --version
          pipenv run ansible-lint -vv --offline
